# Student Marks Sheet – Filtering & Query Assignment

Dataset: `std_marks_sheet.xlsx`

This notebook loads the dataset and answers all 50 filtering/query questions using pandas.

In [1]:
import pandas as pd

df = pd.read_excel("std_marks_sheet.xlsx")
df.head()

  RollNum    Name  Python  NumPy  Pandas  Streamlit  ML  DL  NLP  Total Grade
0    R100   Aarav      86     37      48         82  76  36   67    432     C
1    R101  Vivaan      49     85      82         57  79  37   74    463     C
2    R102  Aditya      95     41      49         96  96  90   73    540     B
3    R103  Vihaan      55     55      96         71  91  93   35    496     B
4    R104   Arjun      58     73      74         78  40  36   45    404     C

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   RollNum    30 non-null     str
 1   Name       30 non-null     str
 2   Python     30 non-null     int64
 3   NumPy      30 non-null     int64
 4   Pandas     30 non-null     int64
 5   Streamlit  30 non-null     int64
 6   ML         30 non-null     int64
 7   DL         30 non-null     int64
 8   NLP        30 non-null     int64
 9   Total      30 non-null     int64
 10  Grade      30 non-null     str
dtypes: int64(8), str(3)
memory usage: 2.7 KB

### Q1. Display all students who scored more than 75 in Python.

In [3]:
df[df["Python"] > 75]

   RollNum    Name  Python  NumPy  Pandas  Streamlit  ML  DL  NLP  Total Grade
0     R100   Aarav      86     37      48         82  76  36   67    432     C
2     R102  Aditya      95     41      49         96  96  90   73    540     B
7     R107   Ayaan      87     94      60         81  78  35   57    492     B
12    R112  Saanvi      98     94      79         61  61  66   94    553     B
13    R113  Aadhya      94     78      99         43  96  66   36    512     B
16    R116    Pari      92     69      42         85  43  51   46    428     C
18    R118   Kiara      83     84      45         86  71  58   66    493     B
19    R119    Riya      93     38      42         38  85  45   43    384     C
20    R120   Kabir      76     36      69         57  78  50   53    419     C
21    R121   Rohan      94     40      69         49  58  93   82    485     C
23    R123   Dhruv      96     38      39         63  66  54   54    410     C
24    R124    Zara      96     88      75         70  86  93   58    566     B
25    R125   Meera      81     97      62         47  96  70   88    541     B
26    R126    Tara      96     52      41         66  92  53   67    467     C
27    R127    Neha      85     78      46         93  86  53   58    499     B
28    R128      Om      89     68      68         62  46  54   70    457     C
29    R129   Rudra      98     96      67        100  73  86   72    592     B

### Q2. Show records of students whose Grade is A.

In [4]:
df[df["Grade"] == "A"]

Empty DataFrame
Columns: [RollNum, Name, Python, NumPy, Pandas, Streamlit, ML, DL, NLP, Total, Grade]
Index: []

### Q3. Find students who scored less than 60 in NumPy.

In [5]:
df[df["NumPy"] < 60]

,RollNum,Name,Python,NumPy,Pandas,Streamlit,ML,DL,NLP,Total,Grade
0,R100,Aarav,86,37,48,82,76,36,67,432,C
2,R102,Aditya,95,41,49,96,96,90,73,540,B
3,R103,Vihaan,55,55,96,71,91,93,35,496,B
5,R105,Sai,37,52,87,69,62,36,91,434,C
6,R106,Reyansh,56,38,58,99,62,88,84,485,C
8,R108,Krishna,36,48,94,37,64,53,65,397,C
9,R109,Ishaan,64,43,75,35,96,36,76,425,C
11,R111,Diya,36,36,49,48,35,78,50,332,D
14,R114,Myra,55,42,43,49,37,89,35,350,C
19,R119,Riya,93,38,42,38,85,45,43,384,C
20,R120,Kabir,76,36,69,57,78,50,53,419,C
21,R121,Rohan,94,40,69,49,58,93,82,485,C
23,R123,Dhruv,96,38,39,63,66,54,54,410,C
26,R126,Tara,96,52,41,66,92,53,67,467,C

### Q4. Display students with Total marks greater than 450.

In [6]:
df[df["Total"] > 450]

,RollNum,Name,Python,NumPy,Pandas,Streamlit,ML,DL,NLP,Total,Grade
1,R101,Vivaan,49,85,82,57,79,37,74,463,C
2,R102,Aditya,95,41,49,96,96,90,73,540,B
3,R103,Vihaan,55,55,96,71,91,93,35,496,B
6,R106,Reyansh,56,38,58,99,62,88,84,485,C
7,R107,Ayaan,87,94,60,81,78,35,57,492,B
10,R110,Ananya,72,87,63,39,96,87,41,485,C
12,R112,Saanvi,98,94,79,61,61,66,94,553,B
13,R113,Aadhya,94,78,99,43,96,66,36,512,B
15,R115,Anika,67,81,35,76,61,90,82,492,B
17,R117,Ira,56,70,97,97,96,72,71,559,B
18,R118,Kiara,83,84,45,86,71,58,66,493,B
21,R121,Rohan,94,40,69,49,58,93,82,485,C
24,R124,Zara,96,88,75,70,86,93,58,566,B
25,R125,Meera,81,97,62,47,96,70,88,541,B
26,R126,Tara,96,52,41,66,92,53,67,467,C
27,R127,Neha,85,78,46,93,86,53,58,499,B
28,R128,Om,89,68,68,62,46,54,70,457,C
29,R129,Rudra,98,96,67,100,73,86,72,592,B

### Q5. Show only name and roll num of students who scored above 80 in Pandas.

In [7]:
df.loc[df["Pandas"] > 80, ["Name", "RollNum"]]

       Name RollNum
1    Vivaan    R101
3    Vihaan    R103
5       Sai    R105
8   Krishna    R108
13   Aadhya    R113
17      Ira    R117

### Q6. Filter students whose Streamlit marks are between 60 and 80.

In [8]:
df[df["Streamlit"].between(60, 80)]

   RollNum    Name  Python  NumPy  Pandas  Streamlit  ML  DL  NLP  Total Grade
3     R103  Vihaan      55     55      96         71  91  93   35    496     B
4     R104   Arjun      58     73      74         78  40  36   45    404     C
5     R105     Sai      37     52      87         69  62  36   91    434     C
12    R112  Saanvi      98     94      79         61  61  66   94    553     B
15    R115   Anika      67     81      35         76  61  90   82    492     B
22    R122   Yusuf      49     88      67         77  93  37   37    448     C
23    R123   Dhruv      96     38      39         63  66  54   54    410     C
24    R124    Zara      96     88      75         70  86  93   58    566     B
26    R126    Tara      96     52      41         66  92  53   67    467     C
28    R128      Om      89     68      68         62  46  54   70    457     C

### Q7. Display students who scored exactly 90 in ML.

In [9]:
df[df["ML"] == 90]

Empty DataFrame
Columns: [RollNum, Name, Python, NumPy, Pandas, Streamlit, ML, DL, NLP, Total, Grade]
Index: []

### Q8. Find students whose DL marks are less than 50.

In [10]:
df[df["DL"] < 50]

   RollNum    Name  Python  NumPy  Pandas  Streamlit  ML  DL  NLP  Total Grade
0     R100   Aarav      86     37      48         82  76  36   67    432     C
1     R101  Vivaan      49     85      82         57  79  37   74    463     C
4     R104   Arjun      58     73      74         78  40  36   45    404     C
5     R105     Sai      37     52      87         69  62  36   91    434     C
7     R107   Ayaan      87     94      60         81  78  35   57    492     B
9     R109  Ishaan      64     43      75         35  96  36   76    425     C
19    R119    Riya      93     38      42         38  85  45   43    384     C
22    R122   Yusuf      49     88      67         77  93  37   37    448     C

### Q9. Show students who scored more than 65 in NLP.

In [11]:
df[df["NLP"] > 65]

,RollNum,Name,Python,NumPy,Pandas,Streamlit,ML,DL,NLP,Total,Grade
0,R100,Aarav,86,37,48,82,76,36,67,432,C
1,R101,Vivaan,49,85,82,57,79,37,74,463,C
2,R102,Aditya,95,41,49,96,96,90,73,540,B
5,R105,Sai,37,52,87,69,62,36,91,434,C
6,R106,Reyansh,56,38,58,99,62,88,84,485,C
9,R109,Ishaan,64,43,75,35,96,36,76,425,C
12,R112,Saanvi,98,94,79,61,61,66,94,553,B
15,R115,Anika,67,81,35,76,61,90,82,492,B
17,R117,Ira,56,70,97,97,96,72,71,559,B
18,R118,Kiara,83,84,45,86,71,58,66,493,B
21,R121,Rohan,94,40,69,49,58,93,82,485,C
25,R125,Meera,81,97,62,47,96,70,88,541,B
26,R126,Tara,96,52,41,66,92,53,67,467,C
28,R128,Om,89,68,68,62,46,54,70,457,C
29,R129,Rudra,98,96,67,100,73,86,72,592,B

### Q10. Display students whose Total marks are less than 400.

In [12]:
df[df["Total"] < 400]

,RollNum,Name,Python,NumPy,Pandas,Streamlit,ML,DL,NLP,Total,Grade
8,R108,Krishna,36,48,94,37,64,53,65,397,C
11,R111,Diya,36,36,49,48,35,78,50,332,D
14,R114,Myra,55,42,43,49,37,89,35,350,C
19,R119,Riya,93,38,42,38,85,45,43,384,C

### Q11. Show students who scored more than 70 in Python and NumPy.

In [13]:
df[(df["Python"] > 70) & (df["NumPy"] > 70)]

   RollNum    Name  Python  NumPy  Pandas  Streamlit  ML  DL  NLP  Total Grade
7     R107   Ayaan      87     94      60         81  78  35   57    492     B
10    R110  Ananya      72     87      63         39  96  87   41    485     C
12    R112  Saanvi      98     94      79         61  61  66   94    553     B
13    R113  Aadhya      94     78      99         43  96  66   36    512     B
18    R118   Kiara      83     84      45         86  71  58   66    493     B
24    R124    Zara      96     88      75         70  86  93   58    566     B
25    R125   Meera      81     97      62         47  96  70   88    541     B
27    R127    Neha      85     78      46         93  86  53   58    499     B
29    R129   Rudra      98     96      67        100  73  86   72    592     B

### Q12. Display students whose Pandas marks are below 60.

In [14]:
df[df["Pandas"] < 60]

,RollNum,Name,Python,NumPy,Pandas,Streamlit,ML,DL,NLP,Total,Grade
0,R100,Aarav,86,37,48,82,76,36,67,432,C
2,R102,Aditya,95,41,49,96,96,90,73,540,B
6,R106,Reyansh,56,38,58,99,62,88,84,485,C
11,R111,Diya,36,36,49,48,35,78,50,332,D
14,R114,Myra,55,42,43,49,37,89,35,350,C
15,R115,Anika,67,81,35,76,61,90,82,492,B
16,R116,Pari,92,69,42,85,43,51,46,428,C
18,R118,Kiara,83,84,45,86,71,58,66,493,B
19,R119,Riya,93,38,42,38,85,45,43,384,C
23,R123,Dhruv,96,38,39,63,66,54,54,410,C
26,R126,Tara,96,52,41,66,92,53,67,467,C
27,R127,Neha,85,78,46,93,86,53,58,499,B

### Q13. Find students with Grade B.

In [15]:
df[df["Grade"] == "B"]

   RollNum    Name  Python  NumPy  Pandas  Streamlit  ML  DL  NLP  Total Grade
2     R102  Aditya      95     41      49         96  96  90   73    540     B
3     R103  Vihaan      55     55      96         71  91  93   35    496     B
7     R107   Ayaan      87     94      60         81  78  35   57    492     B
12    R112  Saanvi      98     94      79         61  61  66   94    553     B
13    R113  Aadhya      94     78      99         43  96  66   36    512     B
15    R115   Anika      67     81      35         76  61  90   82    492     B
17    R117     Ira      56     70      97         97  96  72   71    559     B
18    R118   Kiara      83     84      45         86  71  58   66    493     B
24    R124    Zara      96     88      75         70  86  93   58    566     B
25    R125   Meera      81     97      62         47  96  70   88    541     B
27    R127    Neha      85     78      46         93  86  53   58    499     B
29    R129   Rudra      98     96      67        100  73  86   72    592     B

### Q14. Show students who scored above 85 in ML.

In [16]:
df[df["ML"] > 85]

   RollNum    Name  Python  NumPy  Pandas  Streamlit  ML  DL  NLP  Total Grade
2     R102  Aditya      95     41      49         96  96  90   73    540     B
3     R103  Vihaan      55     55      96         71  91  93   35    496     B
9     R109  Ishaan      64     43      75         35  96  36   76    425     C
10    R110  Ananya      72     87      63         39  96  87   41    485     C
13    R113  Aadhya      94     78      99         43  96  66   36    512     B
17    R117     Ira      56     70      97         97  96  72   71    559     B
22    R122   Yusuf      49     88      67         77  93  37   37    448     C
24    R124    Zara      96     88      75         70  86  93   58    566     B
25    R125   Meera      81     97      62         47  96  70   88    541     B
26    R126    Tara      96     52      41         66  92  53   67    467     C
27    R127    Neha      85     78      46         93  86  53   58    499     B

### Q15. Display students who scored less than 55 in Streamlit.

In [17]:
df[df["Streamlit"] < 55]

,RollNum,Name,Python,NumPy,Pandas,Streamlit,ML,DL,NLP,Total,Grade
8,R108,Krishna,36,48,94,37,64,53,65,397,C
9,R109,Ishaan,64,43,75,35,96,36,76,425,C
10,R110,Ananya,72,87,63,39,96,87,41,485,C
11,R111,Diya,36,36,49,48,35,78,50,332,D
13,R113,Aadhya,94,78,99,43,96,66,36,512,B
14,R114,Myra,55,42,43,49,37,89,35,350,C
19,R119,Riya,93,38,42,38,85,45,43,384,C
21,R121,Rohan,94,40,69,49,58,93,82,485,C
25,R125,Meera,81,97,62,47,96,70,88,541,B

### Q16. Show students whose Python marks are between 60 and 90.

In [18]:
df[df["Python"].between(60, 90)]

   RollNum    Name  Python  NumPy  Pandas  Streamlit  ML  DL  NLP  Total Grade
0     R100   Aarav      86     37      48         82  76  36   67    432     C
7     R107   Ayaan      87     94      60         81  78  35   57    492     B
9     R109  Ishaan      64     43      75         35  96  36   76    425     C
10    R110  Ananya      72     87      63         39  96  87   41    485     C
15    R115   Anika      67     81      35         76  61  90   82    492     B
18    R118   Kiara      83     84      45         86  71  58   66    493     B
20    R120   Kabir      76     36      69         57  78  50   53    419     C
25    R125   Meera      81     97      62         47  96  70   88    541     B
27    R127    Neha      85     78      46         93  86  53   58    499     B
28    R128      Om      89     68      68         62  46  54   70    457     C

### Q17. Find students who scored above 70 in Pandas and NLP.

In [19]:
df[(df["Pandas"] > 70) & (df["NLP"] > 70)]

   RollNum    Name  Python  NumPy  Pandas  Streamlit  ML  DL  NLP  Total Grade
1     R101  Vivaan      49     85      82         57  79  37   74    463     C
5     R105     Sai      37     52      87         69  62  36   91    434     C
9     R109  Ishaan      64     43      75         35  96  36   76    425     C
12    R112  Saanvi      98     94      79         61  61  66   94    553     B
17    R117     Ira      56     70      97         97  96  72   71    559     B

### Q18. Display students whose DL marks are greater than 60.

In [20]:
df[df["DL"] > 60]

,RollNum,Name,Python,NumPy,Pandas,Streamlit,ML,DL,NLP,Total,Grade
2,R102,Aditya,95,41,49,96,96,90,73,540,B
3,R103,Vihaan,55,55,96,71,91,93,35,496,B
6,R106,Reyansh,56,38,58,99,62,88,84,485,C
10,R110,Ananya,72,87,63,39,96,87,41,485,C
11,R111,Diya,36,36,49,48,35,78,50,332,D
12,R112,Saanvi,98,94,79,61,61,66,94,553,B
13,R113,Aadhya,94,78,99,43,96,66,36,512,B
14,R114,Myra,55,42,43,49,37,89,35,350,C
15,R115,Anika,67,81,35,76,61,90,82,492,B
17,R117,Ira,56,70,97,97,96,72,71,559,B
21,R121,Rohan,94,40,69,49,58,93,82,485,C
24,R124,Zara,96,88,75,70,86,93,58,566,B
25,R125,Meera,81,97,62,47,96,70,88,541,B
29,R129,Rudra,98,96,67,100,73,86,72,592,B

### Q19. Show students with Total marks between 400 and 500.

In [21]:
df[df["Total"].between(400, 500)]

,RollNum,Name,Python,NumPy,Pandas,Streamlit,ML,DL,NLP,Total,Grade
0,R100,Aarav,86,37,48,82,76,36,67,432,C
1,R101,Vivaan,49,85,82,57,79,37,74,463,C
3,R103,Vihaan,55,55,96,71,91,93,35,496,B
4,R104,Arjun,58,73,74,78,40,36,45,404,C
5,R105,Sai,37,52,87,69,62,36,91,434,C
6,R106,Reyansh,56,38,58,99,62,88,84,485,C
7,R107,Ayaan,87,94,60,81,78,35,57,492,B
9,R109,Ishaan,64,43,75,35,96,36,76,425,C
10,R110,Ananya,72,87,63,39,96,87,41,485,C
15,R115,Anika,67,81,35,76,61,90,82,492,B
16,R116,Pari,92,69,42,85,43,51,46,428,C
18,R118,Kiara,83,84,45,86,71,58,66,493,B
20,R120,Kabir,76,36,69,57,78,50,53,419,C
21,R121,Rohan,94,40,69,49,58,93,82,485,C
22,R122,Yusuf,49,88,67,77,93,37,37,448,C
23,R123,Dhruv,96,38,39,63,66,54,54,410,C
26,R126,Tara,96,52,41,66,92,53,67,467,C
27,R127,Neha,85,78,46,93,86,53,58,499,B
28,R128,Om,89,68,68,62,46,54,70,457,C

### Q20. Display students who scored less than 65 in ML.

In [22]:
df[df["ML"] < 65]

,RollNum,Name,Python,NumPy,Pandas,Streamlit,ML,DL,NLP,Total,Grade
4,R104,Arjun,58,73,74,78,40,36,45,404,C
5,R105,Sai,37,52,87,69,62,36,91,434,C
6,R106,Reyansh,56,38,58,99,62,88,84,485,C
8,R108,Krishna,36,48,94,37,64,53,65,397,C
11,R111,Diya,36,36,49,48,35,78,50,332,D
12,R112,Saanvi,98,94,79,61,61,66,94,553,B
14,R114,Myra,55,42,43,49,37,89,35,350,C
15,R115,Anika,67,81,35,76,61,90,82,492,B
16,R116,Pari,92,69,42,85,43,51,46,428,C
21,R121,Rohan,94,40,69,49,58,93,82,485,C
28,R128,Om,89,68,68,62,46,54,70,457,C

### Q21. Show students who scored above 75 in NumPy.

In [23]:
df[df["NumPy"] > 75]

   RollNum    Name  Python  NumPy  Pandas  Streamlit  ML  DL  NLP  Total Grade
1     R101  Vivaan      49     85      82         57  79  37   74    463     C
7     R107   Ayaan      87     94      60         81  78  35   57    492     B
10    R110  Ananya      72     87      63         39  96  87   41    485     C
12    R112  Saanvi      98     94      79         61  61  66   94    553     B
13    R113  Aadhya      94     78      99         43  96  66   36    512     B
15    R115   Anika      67     81      35         76  61  90   82    492     B
18    R118   Kiara      83     84      45         86  71  58   66    493     B
22    R122   Yusuf      49     88      67         77  93  37   37    448     C
24    R124    Zara      96     88      75         70  86  93   58    566     B
25    R125   Meera      81     97      62         47  96  70   88    541     B
27    R127    Neha      85     78      46         93  86  53   58    499     B
29    R129   Rudra      98     96      67        100  73  86   72    592     B

### Q22. Find students whose NLP marks are less than 50.

In [24]:
df[df["NLP"] < 50]

   RollNum    Name  Python  NumPy  Pandas  Streamlit  ML  DL  NLP  Total Grade
3     R103  Vihaan      55     55      96         71  91  93   35    496     B
4     R104   Arjun      58     73      74         78  40  36   45    404     C
10    R110  Ananya      72     87      63         39  96  87   41    485     C
13    R113  Aadhya      94     78      99         43  96  66   36    512     B
14    R114    Myra      55     42      43         49  37  89   35    350     C
16    R116    Pari      92     69      42         85  43  51   46    428     C
19    R119    Riya      93     38      42         38  85  45   43    384     C
22    R122   Yusuf      49     88      67         77  93  37   37    448     C

### Q23. Display students who scored more than 80 in Streamlit.

In [25]:
df[df["Streamlit"] > 80]

,RollNum,Name,Python,NumPy,Pandas,Streamlit,ML,DL,NLP,Total,Grade
0,R100,Aarav,86,37,48,82,76,36,67,432,C
2,R102,Aditya,95,41,49,96,96,90,73,540,B
6,R106,Reyansh,56,38,58,99,62,88,84,485,C
7,R107,Ayaan,87,94,60,81,78,35,57,492,B
16,R116,Pari,92,69,42,85,43,51,46,428,C
17,R117,Ira,56,70,97,97,96,72,71,559,B
18,R118,Kiara,83,84,45,86,71,58,66,493,B
27,R127,Neha,85,78,46,93,86,53,58,499,B
29,R129,Rudra,98,96,67,100,73,86,72,592,B

### Q24. Show students with Grade C.

In [26]:
df[df["Grade"] == "C"]

,RollNum,Name,Python,NumPy,Pandas,Streamlit,ML,DL,NLP,Total,Grade
0,R100,Aarav,86,37,48,82,76,36,67,432,C
1,R101,Vivaan,49,85,82,57,79,37,74,463,C
4,R104,Arjun,58,73,74,78,40,36,45,404,C
5,R105,Sai,37,52,87,69,62,36,91,434,C
6,R106,Reyansh,56,38,58,99,62,88,84,485,C
8,R108,Krishna,36,48,94,37,64,53,65,397,C
9,R109,Ishaan,64,43,75,35,96,36,76,425,C
10,R110,Ananya,72,87,63,39,96,87,41,485,C
14,R114,Myra,55,42,43,49,37,89,35,350,C
16,R116,Pari,92,69,42,85,43,51,46,428,C
19,R119,Riya,93,38,42,38,85,45,43,384,C
20,R120,Kabir,76,36,69,57,78,50,53,419,C
21,R121,Rohan,94,40,69,49,58,93,82,485,C
22,R122,Yusuf,49,88,67,77,93,37,37,448,C
23,R123,Dhruv,96,38,39,63,66,54,54,410,C
26,R126,Tara,96,52,41,66,92,53,67,467,C
28,R128,Om,89,68,68,62,46,54,70,457,C

### Q25. Display students who scored exactly 100 in Python.

In [27]:
df[df["Python"] == 100]

Empty DataFrame
Columns: [RollNum, Name, Python, NumPy, Pandas, Streamlit, ML, DL, NLP, Total, Grade]
Index: []

### Q26. Display students who scored more than 70 in Python and more than 65 in Pandas.

In [28]:
df[(df["Python"] > 70) & (df["Pandas"] > 65)]

   RollNum    Name  Python  NumPy  Pandas  Streamlit  ML  DL  NLP  Total Grade
12    R112  Saanvi      98     94      79         61  61  66   94    553     B
13    R113  Aadhya      94     78      99         43  96  66   36    512     B
20    R120   Kabir      76     36      69         57  78  50   53    419     C
21    R121   Rohan      94     40      69         49  58  93   82    485     C
24    R124    Zara      96     88      75         70  86  93   58    566     B
28    R128      Om      89     68      68         62  46  54   70    457     C
29    R129   Rudra      98     96      67        100  73  86   72    592     B

### Q27. Find students who scored less than 60 in ML or less than 50 in DL.

In [29]:
df[(df["ML"] < 60) | (df["DL"] < 50)]

   RollNum    Name  Python  NumPy  Pandas  Streamlit  ML  DL  NLP  Total Grade
0     R100   Aarav      86     37      48         82  76  36   67    432     C
1     R101  Vivaan      49     85      82         57  79  37   74    463     C
4     R104   Arjun      58     73      74         78  40  36   45    404     C
5     R105     Sai      37     52      87         69  62  36   91    434     C
7     R107   Ayaan      87     94      60         81  78  35   57    492     B
9     R109  Ishaan      64     43      75         35  96  36   76    425     C
11    R111    Diya      36     36      49         48  35  78   50    332     D
14    R114    Myra      55     42      43         49  37  89   35    350     C
16    R116    Pari      92     69      42         85  43  51   46    428     C
19    R119    Riya      93     38      42         38  85  45   43    384     C
21    R121   Rohan      94     40      69         49  58  93   82    485     C
22    R122   Yusuf      49     88      67         77  93  37   37    448     C
28    R128      Om      89     68      68         62  46  54   70    457     C

### Q28. Display students with Grade A and NLP marks greater than 60.

In [30]:
df[(df["Grade"] == "A") & (df["NLP"] > 60)]

Empty DataFrame
Columns: [RollNum, Name, Python, NumPy, Pandas, Streamlit, ML, DL, NLP, Total, Grade]
Index: []

### Q29. Show students whose Total marks are above 500 and Streamlit marks below 60.

In [31]:
df[(df["Total"] > 500) & (df["Streamlit"] < 60)]

   RollNum    Name  Python  NumPy  Pandas  Streamlit  ML  DL  NLP  Total Grade
13    R113  Aadhya      94     78      99         43  96  66   36    512     B
25    R125   Meera      81     97      62         47  96  70   88    541     B

### Q30. Display students who scored more than 75 in Python, NumPy, and Pandas.

In [32]:
df[(df["Python"] > 75) & (df["NumPy"] > 75) & (df["Pandas"] > 75)]

   RollNum    Name  Python  NumPy  Pandas  Streamlit  ML  DL  NLP  Total Grade
12    R112  Saanvi      98     94      79         61  61  66   94    553     B
13    R113  Aadhya      94     78      99         43  96  66   36    512     B

### Q31. Find students who scored less than 50 in Python and NumPy.

In [33]:
df[(df["Python"] < 50) & (df["NumPy"] < 50)]

,RollNum,Name,Python,NumPy,Pandas,Streamlit,ML,DL,NLP,Total,Grade
8,R108,Krishna,36,48,94,37,64,53,65,397,C
11,R111,Diya,36,36,49,48,35,78,50,332,D

### Q32. Display students whose ML and DL marks are both greater than 60.

In [34]:
df[(df["ML"] > 60) & (df["DL"] > 60)]

,RollNum,Name,Python,NumPy,Pandas,Streamlit,ML,DL,NLP,Total,Grade
2,R102,Aditya,95,41,49,96,96,90,73,540,B
3,R103,Vihaan,55,55,96,71,91,93,35,496,B
6,R106,Reyansh,56,38,58,99,62,88,84,485,C
10,R110,Ananya,72,87,63,39,96,87,41,485,C
12,R112,Saanvi,98,94,79,61,61,66,94,553,B
13,R113,Aadhya,94,78,99,43,96,66,36,512,B
15,R115,Anika,67,81,35,76,61,90,82,492,B
17,R117,Ira,56,70,97,97,96,72,71,559,B
24,R124,Zara,96,88,75,70,86,93,58,566,B
25,R125,Meera,81,97,62,47,96,70,88,541,B
29,R129,Rudra,98,96,67,100,73,86,72,592,B

### Q33. Show students who scored more than 80 in Python but less than 60 in NLP.

In [35]:
df[(df["Python"] > 80) & (df["NLP"] < 60)]

   RollNum    Name  Python  NumPy  Pandas  Streamlit  ML  DL  NLP  Total Grade
7     R107   Ayaan      87     94      60         81  78  35   57    492     B
13    R113  Aadhya      94     78      99         43  96  66   36    512     B
16    R116    Pari      92     69      42         85  43  51   46    428     C
19    R119    Riya      93     38      42         38  85  45   43    384     C
23    R123   Dhruv      96     38      39         63  66  54   54    410     C
24    R124    Zara      96     88      75         70  86  93   58    566     B
27    R127    Neha      85     78      46         93  86  53   58    499     B

### Q34. Display students whose Total marks are below 450 and Grade is B.

In [36]:
df[(df["Total"] < 450) & (df["Grade"] == "B")]

Empty DataFrame
Columns: [RollNum, Name, Python, NumPy, Pandas, Streamlit, ML, DL, NLP, Total, Grade]
Index: []

### Q35. Find students who scored more than 70 in Pandas or NLP.

In [37]:
df[(df["Pandas"] > 70) | (df["NLP"] > 70)]

,RollNum,Name,Python,NumPy,Pandas,Streamlit,ML,DL,NLP,Total,Grade
1,R101,Vivaan,49,85,82,57,79,37,74,463,C
2,R102,Aditya,95,41,49,96,96,90,73,540,B
3,R103,Vihaan,55,55,96,71,91,93,35,496,B
4,R104,Arjun,58,73,74,78,40,36,45,404,C
5,R105,Sai,37,52,87,69,62,36,91,434,C
6,R106,Reyansh,56,38,58,99,62,88,84,485,C
8,R108,Krishna,36,48,94,37,64,53,65,397,C
9,R109,Ishaan,64,43,75,35,96,36,76,425,C
12,R112,Saanvi,98,94,79,61,61,66,94,553,B
13,R113,Aadhya,94,78,99,43,96,66,36,512,B
15,R115,Anika,67,81,35,76,61,90,82,492,B
17,R117,Ira,56,70,97,97,96,72,71,559,B
21,R121,Rohan,94,40,69,49,58,93,82,485,C
24,R124,Zara,96,88,75,70,86,93,58,566,B
25,R125,Meera,81,97,62,47,96,70,88,541,B
29,R129,Rudra,98,96,67,100,73,86,72,592,B

### Q36. Show students who scored below 60 in all of Python, NumPy, and Pandas.

In [38]:
df[(df["Python"] < 60) & (df["NumPy"] < 60) & (df["Pandas"] < 60)]

,RollNum,Name,Python,NumPy,Pandas,Streamlit,ML,DL,NLP,Total,Grade
6,R106,Reyansh,56,38,58,99,62,88,84,485,C
11,R111,Diya,36,36,49,48,35,78,50,332,D
14,R114,Myra,55,42,43,49,37,89,35,350,C

### Q37. Display students who scored above 65 in ML and NLP.

In [39]:
df[(df["ML"] > 65) & (df["NLP"] > 65)]

   RollNum    Name  Python  NumPy  Pandas  Streamlit  ML  DL  NLP  Total Grade
0     R100   Aarav      86     37      48         82  76  36   67    432     C
1     R101  Vivaan      49     85      82         57  79  37   74    463     C
2     R102  Aditya      95     41      49         96  96  90   73    540     B
9     R109  Ishaan      64     43      75         35  96  36   76    425     C
17    R117     Ira      56     70      97         97  96  72   71    559     B
18    R118   Kiara      83     84      45         86  71  58   66    493     B
25    R125   Meera      81     97      62         47  96  70   88    541     B
26    R126    Tara      96     52      41         66  92  53   67    467     C
29    R129   Rudra      98     96      67        100  73  86   72    592     B

### Q38. Find students with Grade A but DL marks less than 55.

In [40]:
df[(df["Grade"] == "A") & (df["DL"] < 55)]

Empty DataFrame
Columns: [RollNum, Name, Python, NumPy, Pandas, Streamlit, ML, DL, NLP, Total, Grade]
Index: []

### Q39. Show students whose Streamlit and Pandas marks are both above 70.

In [41]:
df[(df["Streamlit"] > 70) & (df["Pandas"] > 70)]

   RollNum    Name  Python  NumPy  Pandas  Streamlit  ML  DL  NLP  Total Grade
3     R103  Vihaan      55     55      96         71  91  93   35    496     B
4     R104   Arjun      58     73      74         78  40  36   45    404     C
17    R117     Ira      56     70      97         97  96  72   71    559     B

### Q40. Display students who scored less than 50 in at least one subject.

In [42]:
subjects = ["Python", "NumPy", "Pandas", "Streamlit", "ML", "DL", "NLP"]
df[(df[subjects] < 50).any(axis=1)]

,RollNum,Name,Python,NumPy,Pandas,Streamlit,ML,DL,NLP,Total,Grade
0,R100,Aarav,86,37,48,82,76,36,67,432,C
1,R101,Vivaan,49,85,82,57,79,37,74,463,C
2,R102,Aditya,95,41,49,96,96,90,73,540,B
3,R103,Vihaan,55,55,96,71,91,93,35,496,B
4,R104,Arjun,58,73,74,78,40,36,45,404,C
5,R105,Sai,37,52,87,69,62,36,91,434,C
6,R106,Reyansh,56,38,58,99,62,88,84,485,C
7,R107,Ayaan,87,94,60,81,78,35,57,492,B
8,R108,Krishna,36,48,94,37,64,53,65,397,C
9,R109,Ishaan,64,43,75,35,96,36,76,425,C
10,R110,Ananya,72,87,63,39,96,87,41,485,C
11,R111,Diya,36,36,49,48,35,78,50,332,D
13,R113,Aadhya,94,78,99,43,96,66,36,512,B
14,R114,Myra,55,42,43,49,37,89,35,350,C
15,R115,Anika,67,81,35,76,61,90,82,492,B
16,R116,Pari,92,69,42,85,43,51,46,428,C
18,R118,Kiara,83,84,45,86,71,58,66,493,B
19,R119,Riya,93,38,42,38,85,45,43,384,C
20,R120,Kabir,76,36,69,57,78,50,53,419,C
21,R121,Rohan,94,40,69,49,58,93,82,485,C
22,R122,Yusuf,49,88,67,77,93,37,37,448,C
23,R123,Dhruv,96,38,39,63,66,54,54,410,C
25,R125,Meera,81,97,62,47,96,70,88,541,B
26,R126,Tara,96,52,41,66,92,53,67,467,C
27,R127,Neha,85,78,46,93,86,53,58,499,B
28,R128,Om,89,68,68,62,46,54,70,457,C

### Q41. Find students who scored above 90 in any one subject.

In [43]:
df[(df[subjects] > 90).any(axis=1)]

,RollNum,Name,Python,NumPy,Pandas,Streamlit,ML,DL,NLP,Total,Grade
2,R102,Aditya,95,41,49,96,96,90,73,540,B
3,R103,Vihaan,55,55,96,71,91,93,35,496,B
5,R105,Sai,37,52,87,69,62,36,91,434,C
6,R106,Reyansh,56,38,58,99,62,88,84,485,C
7,R107,Ayaan,87,94,60,81,78,35,57,492,B
8,R108,Krishna,36,48,94,37,64,53,65,397,C
9,R109,Ishaan,64,43,75,35,96,36,76,425,C
10,R110,Ananya,72,87,63,39,96,87,41,485,C
12,R112,Saanvi,98,94,79,61,61,66,94,553,B
13,R113,Aadhya,94,78,99,43,96,66,36,512,B
16,R116,Pari,92,69,42,85,43,51,46,428,C
17,R117,Ira,56,70,97,97,96,72,71,559,B
19,R119,Riya,93,38,42,38,85,45,43,384,C
21,R121,Rohan,94,40,69,49,58,93,82,485,C
22,R122,Yusuf,49,88,67,77,93,37,37,448,C
23,R123,Dhruv,96,38,39,63,66,54,54,410,C
24,R124,Zara,96,88,75,70,86,93,58,566,B
25,R125,Meera,81,97,62,47,96,70,88,541,B
26,R126,Tara,96,52,41,66,92,53,67,467,C
27,R127,Neha,85,78,46,93,86,53,58,499,B
29,R129,Rudra,98,96,67,100,73,86,72,592,B

### Q42. Display students whose Total marks are between 480 and 520.

In [44]:
df[df["Total"].between(480, 520)]

,RollNum,Name,Python,NumPy,Pandas,Streamlit,ML,DL,NLP,Total,Grade
3,R103,Vihaan,55,55,96,71,91,93,35,496,B
6,R106,Reyansh,56,38,58,99,62,88,84,485,C
7,R107,Ayaan,87,94,60,81,78,35,57,492,B
10,R110,Ananya,72,87,63,39,96,87,41,485,C
13,R113,Aadhya,94,78,99,43,96,66,36,512,B
15,R115,Anika,67,81,35,76,61,90,82,492,B
18,R118,Kiara,83,84,45,86,71,58,66,493,B
21,R121,Rohan,94,40,69,49,58,93,82,485,C
27,R127,Neha,85,78,46,93,86,53,58,499,B

### Q43. Show students who scored more than 60 in Python and less than 60 in NumPy.

In [45]:
df[(df["Python"] > 60) & (df["NumPy"] < 60)]

   RollNum    Name  Python  NumPy  Pandas  Streamlit  ML  DL  NLP  Total Grade
0     R100   Aarav      86     37      48         82  76  36   67    432     C
2     R102  Aditya      95     41      49         96  96  90   73    540     B
9     R109  Ishaan      64     43      75         35  96  36   76    425     C
19    R119    Riya      93     38      42         38  85  45   43    384     C
20    R120   Kabir      76     36      69         57  78  50   53    419     C
21    R121   Rohan      94     40      69         49  58  93   82    485     C
23    R123   Dhruv      96     38      39         63  66  54   54    410     C
26    R126    Tara      96     52      41         66  92  53   67    467     C

### Q44. Display students with Grade B and ML marks above 70.

In [46]:
df[(df["Grade"] == "B") & (df["ML"] > 70)]

   RollNum    Name  Python  NumPy  Pandas  Streamlit  ML  DL  NLP  Total Grade
2     R102  Aditya      95     41      49         96  96  90   73    540     B
3     R103  Vihaan      55     55      96         71  91  93   35    496     B
7     R107   Ayaan      87     94      60         81  78  35   57    492     B
13    R113  Aadhya      94     78      99         43  96  66   36    512     B
17    R117     Ira      56     70      97         97  96  72   71    559     B
18    R118   Kiara      83     84      45         86  71  58   66    493     B
24    R124    Zara      96     88      75         70  86  93   58    566     B
25    R125   Meera      81     97      62         47  96  70   88    541     B
27    R127    Neha      85     78      46         93  86  53   58    499     B
29    R129   Rudra      98     96      67        100  73  86   72    592     B

### Q45. Find students whose NLP marks are greater than DL marks.

In [47]:
df[df["NLP"] > df["DL"]]

,RollNum,Name,Python,NumPy,Pandas,Streamlit,ML,DL,NLP,Total,Grade
0,R100,Aarav,86,37,48,82,76,36,67,432,C
1,R101,Vivaan,49,85,82,57,79,37,74,463,C
4,R104,Arjun,58,73,74,78,40,36,45,404,C
5,R105,Sai,37,52,87,69,62,36,91,434,C
7,R107,Ayaan,87,94,60,81,78,35,57,492,B
8,R108,Krishna,36,48,94,37,64,53,65,397,C
9,R109,Ishaan,64,43,75,35,96,36,76,425,C
12,R112,Saanvi,98,94,79,61,61,66,94,553,B
18,R118,Kiara,83,84,45,86,71,58,66,493,B
20,R120,Kabir,76,36,69,57,78,50,53,419,C
25,R125,Meera,81,97,62,47,96,70,88,541,B
26,R126,Tara,96,52,41,66,92,53,67,467,C
27,R127,Neha,85,78,46,93,86,53,58,499,B
28,R128,Om,89,68,68,62,46,54,70,457,C

### Q46. Display students who scored above 70 in Python, NumPy, and Pandas.

In [48]:
df[(df["Python"] > 70) & (df["NumPy"] > 70) & (df["Pandas"] > 70)]

   RollNum    Name  Python  NumPy  Pandas  Streamlit  ML  DL  NLP  Total Grade
12    R112  Saanvi      98     94      79         61  61  66   94    553     B
13    R113  Aadhya      94     78      99         43  96  66   36    512     B
24    R124    Zara      96     88      75         70  86  93   58    566     B

### Q47. Find students whose Python + NumPy + Pandas total is greater than 200.

In [49]:
df[(df["Python"] + df["NumPy"] + df["Pandas"]) > 200]

   RollNum    Name  Python  NumPy  Pandas  Streamlit  ML  DL  NLP  Total Grade
1     R101  Vivaan      49     85      82         57  79  37   74    463     C
3     R103  Vihaan      55     55      96         71  91  93   35    496     B
4     R104   Arjun      58     73      74         78  40  36   45    404     C
7     R107   Ayaan      87     94      60         81  78  35   57    492     B
10    R110  Ananya      72     87      63         39  96  87   41    485     C
12    R112  Saanvi      98     94      79         61  61  66   94    553     B
13    R113  Aadhya      94     78      99         43  96  66   36    512     B
16    R116    Pari      92     69      42         85  43  51   46    428     C
17    R117     Ira      56     70      97         97  96  72   71    559     B
18    R118   Kiara      83     84      45         86  71  58   66    493     B
21    R121   Rohan      94     40      69         49  58  93   82    485     C
22    R122   Yusuf      49     88      67         77  93  37   37    448     C
24    R124    Zara      96     88      75         70  86  93   58    566     B
25    R125   Meera      81     97      62         47  96  70   88    541     B
27    R127    Neha      85     78      46         93  86  53   58    499     B
28    R128      Om      89     68      68         62  46  54   70    457     C
29    R129   Rudra      98     96      67        100  73  86   72    592     B

### Q48. Display students who scored the maximum marks in ML.

In [50]:
df[df["ML"] == df["ML"].max()]

   RollNum    Name  Python  NumPy  Pandas  Streamlit  ML  DL  NLP  Total Grade
2     R102  Aditya      95     41      49         96  96  90   73    540     B
9     R109  Ishaan      64     43      75         35  96  36   76    425     C
10    R110  Ananya      72     87      63         39  96  87   41    485     C
13    R113  Aadhya      94     78      99         43  96  66   36    512     B
17    R117     Ira      56     70      97         97  96  72   71    559     B
25    R125   Meera      81     97      62         47  96  70   88    541     B

### Q49. Show students who scored the minimum marks in DL.

In [51]:
df[df["DL"] == df["DL"].min()]

  RollNum   Name  Python  NumPy  Pandas  Streamlit  ML  DL  NLP  Total Grade
7    R107  Ayaan      87     94      60         81  78  35   57    492     B

### Q50. Display students whose Total marks are above the dataset average.

In [52]:
df[df["Total"] > df["Total"].mean()]

,RollNum,Name,Python,NumPy,Pandas,Streamlit,ML,DL,NLP,Total,Grade
2,R102,Aditya,95,41,49,96,96,90,73,540,B
3,R103,Vihaan,55,55,96,71,91,93,35,496,B
6,R106,Reyansh,56,38,58,99,62,88,84,485,C
7,R107,Ayaan,87,94,60,81,78,35,57,492,B
10,R110,Ananya,72,87,63,39,96,87,41,485,C
12,R112,Saanvi,98,94,79,61,61,66,94,553,B
13,R113,Aadhya,94,78,99,43,96,66,36,512,B
15,R115,Anika,67,81,35,76,61,90,82,492,B
17,R117,Ira,56,70,97,97,96,72,71,559,B
18,R118,Kiara,83,84,45,86,71,58,66,493,B
21,R121,Rohan,94,40,69,49,58,93,82,485,C
24,R124,Zara,96,88,75,70,86,93,58,566,B
25,R125,Meera,81,97,62,47,96,70,88,541,B
27,R127,Neha,85,78,46,93,86,53,58,499,B
29,R129,Rudra,98,96,67,100,73,86,72,592,B